version: '2'

services:

  vault-ui:
    image: djenriquez/vault-ui:2.3.0
    environment:
      VAULT_URL_DEFAULT: https://${VAULT_DOMAIN}
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host: ${VAULTUI_DOMAIN}"
      traefik.port: '8000'

  vault:
    privileged: true
    image: vault:0.9.5
    environment:
      VAULT_LOCAL_CONFIG: '{ "storage": { "azure": { "accountName": "${AZURE_ACCOUNT_NAME}",
        "accountKey": "${AZURE_ACCOUNT_KEY}",
        "container": "${AZURE_ACCOUNT_CONTAINER}" } }, "listener": { "tcp": { "address": "0.0.0.0:8200",
        "tls_disable": 1 } } }'
    command:
    - server
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host: ${VAULT_DOMAIN}"
      traefik.port: '8200'
    logging:
      driver: splunk
      options:
        splunk-format: json
        splunk-insecureskipverify: 'true'
        splunk-source: vault-audit
        splunk-sourcetype: stdout
        splunk-token: ${SPLUNK_TOKEN}
        splunk-url: ${SPLUNK_URL}
        splunk-verify-connection: 'false'
        tag: imagename={{.ImageName}} containername={{.Name}} containerid={{.FullID}}
