version: '2'

services:

  vault-ui:
    image: djenriquez/vault-ui
    environment:
      VAULT_URL_DEFAULT: https://${VAULT_DOMAIN}
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host: vault-ui.nhschoices.net"
      traefik.port: '8000'

  vault:
    privileged: true
    image: vault:0.7.3
    environment:
      VAULT_LOCAL_CONFIG: '{ "storage": { "azure": { "accountName": "${AZURE_ACCOUNT_NAME}",
        "accountKey": "${AZURE_ACCOUNT_KEY}",
        "container": "${AZURE_ACCOUNT_CONTAINER}" } }, "listener": { "tcp": { "address": "0.0.0.0:8200",
        "tls_disable": 1 } } }'
    command:
    - server
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host: vault.nhschoices.net"
      traefik.port: '8200'
